config/routes.rb
Rails.application.routes.draw do

  get 'breweries/new'

  get 'breweries/create'

  get 'breweries/index'

  get 'breweries/destroy'

  root   'taps#index'
  resources :styles
  resources :breweries
  resources :pubs
  resources :priorities
  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => :my
  resources :users
  resources :kegs
  resources :beers
  resources :taps
end

app/models/priority.rb
class Priority < ApplicationRecord
  belongs_to :brewery, optional: true
  belongs_to :beer, optional: true
  belongs_to :style, optional: true
  belongs_to :tap

  validates :beer_id, allow_blank: true, uniqueness: {scope: [:tap_id]}
  validates :brewery_id, allow_blank: true, uniqueness: {scope: [:tap_id]}
  validates :style_id, allow_blank: true, uniqueness: {scope: [:tap_id]}

  scope :wanted, -> {where(wanted: true)}
  scope :not_wanted, -> {where(wanted: false)}
  scope :p_beers, -> {where(p_type: :p_beer)}
  scope :p_breweries, -> {where(p_type: :p_brewery )}
  scope :p_styles, -> {where(p_type: :p_style )}

  enum p_type: {same_beer: 0, p_beer: 1, p_brewery: 2, p_style: 3}

  def prioritize
    wanted == true ? w = "Prioritize " : w = "Avoid "
    return w + "beer: " + beer.name if same_beer? || p_beer?
    return w + "brewery: " + brewery.name if p_brewery?
    return w + "style: " + style.name if p_style?
  end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  load_and_authorize_resource
  before_action :set_priority, only: [:show, :edit, :update, :destroy]

  # GET /priorities
  # GET /priorities.json
  def index
    @priorities = Priority.all
  end

  # GET /priorities/1
  # GET /priorities/1.json
  def show
  end

  # GET /priorities/new
  def new
    @priority = Priority.new
  end

  # GET /priorities/1/edit
  def edit
  end

  # POST /priorities
  # POST /priorities.json

    def create
      @priority = Priority.new(priority_params)
      if @priority.save
        flash[:notice] = "Priority created!"
        redirect_to edit_tap_path(@priority.tap_id)
      else
        flash[:error] = "You can't leave empty priorities!"
        redirect_to edit_tap_path(@priority.tap_id)
      end
    end

  # PATCH/PUT /priorities/1
  # PATCH/PUT /priorities/1.json
  def update
    respond_to do |format|
      if @priority.update(priority_params)
        format.html { redirect_to @priority, notice: 'Priority was successfully updated.' }
        format.json { render :show, status: :ok, location: @priority }
      else
        format.html { render :edit }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /priorities/1
  # DELETE /priorities/1.json
  def destroy
    @tap = @priority.tap
    @priority.destroy
    respond_to do |format|
      format.html { redirect_to edit_tap_path(@tap), notice: 'Priority was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_priority
      @priority = Priority.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def priority_params
      params.require(:priority).permit(:wanted, :beer_id, :brewery_id, :style_id, :p_type, :tap_id)
    end
end

app/views/priorities/_new.html.erb
<h3>Priorities: </h3>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% if @tap.keg %>
    <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Continue with the same beer
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <%= render "priorities/same_beer" %>
      </div>
    </div>
  </div>
  <% end %>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Add beer priority
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
          <%= render "priorities/p_beer" %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Add brewry priority
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <%= render "priorities/p_brewery" %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Add style priority
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
          <%= render "priorities/p_style" %>
      </div>
    </div>
  </div>
</div>

app/views/priorities/_p_beer.html.erb
<%= form_for Priority.new do |f| %>

  <div class="field form-field">
    <%= f.select :wanted, options_for_select([['Prioritize', true], ['Avoid', false]])%>
  </div>

  <div class="field form-field">
    <%= f.hidden_field :p_type, value: :p_beer %>
  </div>

  <div class="field form-field">
    <%= f.hidden_field :tap_id, value: @tap.id %>
  </div>

    <% @beers = Beer.all %>
    <%= f.select :beer_id,
        @beers.map { |b| [b.name, b.id  ] }, {} %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/priorities/_p_brewery.html.erb
<%= form_for Priority.new do |f| %>

<div class="field form-field">
  <%= f.select :wanted, options_for_select([['Prioritize', true], ['Avoid', false]])%>
</div>

  <div class="field">
    <%= f.hidden_field :p_type, value: :p_brewery %>
  </div>

  <div class="field">
    <%= f.hidden_field :tap_id, value: @tap.id %>
  </div>

    <% @breweries = Brewery.all %>
    <%= f.select :brewery_id,
        @breweries.map { |b| [b.name, b.id  ] }, {} %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/priorities/_p_style.html.erb
<%= form_for Priority.new do |f| %>

<div class="field form-field">
  <%= f.select :wanted, options_for_select([['Prioritize', true], ['Avoid', false]])%>
</div>

  <div class="field">
    <%= f.hidden_field :p_type, value: :p_style %>
  </div>

  <div class="field">
    <%= f.hidden_field :tap_id, value: @tap.id %>
  </div>

    <% @styles = Style.all %>
    <%= f.select :style_id,
        @styles.map { |s| [s.name, s.id  ] }, {} %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/priorities/_same_beer.html.erb
<h4>Continiue with <%= @tap.keg.beer.name %></h4>
<%= form_for Priority.new do |f| %>
  <div class="field">
    <%= f.hidden_field :wanted, value: true %>
  </div>

  <div class="field">
    <%= f.hidden_field :beer_id, value: @tap.keg.beer_id %>
  </div>

  <div class="field">
    <%= f.hidden_field :p_type, value: :same_beer %>
  </div>

  <div class="field">
    <%= f.hidden_field :tap_id, value: @tap.id %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/priorities/edit.html.erb
<h1>Editing Priority</h1>

<%= render 'form', priority: @priority %>

<%= link_to 'Show', @priority %> |
<%= link_to 'Back', priorities_path %>

app/views/priorities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Priorities</h1>

<table>
  <thead>
    <tr>
      <th>Wanted</th>
      <th>Beer</th>
      <th>Brewery</th>
      <th>Style</th>
      <th>P type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @priorities.each do |priority| %>
      <tr>
        <td><%= priority.wanted %></td>
        <td><%= priority.beer %></td>
        <td><%= priority.brewery %></td>
        <td><%= priority.style %></td>
        <td><%= priority.p_type %></td>
        <td><%= link_to 'Show', priority %></td>
        <td><%= link_to 'Edit', edit_priority_path(priority) %></td>
        <td><%= link_to 'Destroy', priority, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer Priority', new_priority_path(p_params: 1) %>
<%= link_to 'New Brewery Priority', new_priority_path(p_params: 2) %>
<%= link_to 'New Style Priority', new_priority_path(p_params: 3) %>