config/routes.rb
Rails.application.routes.draw do

  get 'breweries/new'

  get 'breweries/create'

  get 'breweries/index'

  get 'breweries/destroy'

  root   'taps#index'
  resources :styles
  resources :breweries
  resources :pubs
  resources :priorities
  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => :my
  resources :users
  resources :kegs
  resources :beers
  resources :taps
end

app/models/tap.rb
class Tap < ApplicationRecord
  before_save :set_number

  has_one :keg
  has_many :priorities
  belongs_to :pub
  accepts_nested_attributes_for :keg, update_only: true
  accepts_nested_attributes_for :priorities

  def set_number
    self.number = self.pub.taps.count+1
  end

  def beer_picker
    results = []
    results << self.pub.kegs.where(beer_id: keg.beer_id, in_use: false).select('MIN(expiration_date), *').first if priorities.same_beer.any? && self.pub.kegs.where(in_use: false, beer_id: keg.beer_id).any?
    return results unless results.empty?
    results = priority_beers('wanted') - priority_beers('not_wanted')
    results.first(3)
  end

 private

  def priority_beers wanted
      beers = priorities.send(wanted).p_beers.pluck(:beer_id)
      beers = self.pub.kegs.avaiable_beers.includes(:beer).where(beers: {id: beers})
      beers ||= []

      breweries = priorities.send(wanted).p_breweries.pluck(:brewery_id)
      breweries = self.pub.kegs.avaiable_beers.includes(:beer).where(beers: {brewery_id: breweries})
      breweries ||= []

      styles = priorities.send(wanted).p_styles.pluck(:style_id)
      styles = self.pub.kegs.avaiable_beers.includes(:beer).where(beers: {style_id: styles})
      styles ||= []

      compared ||= beers + breweries + styles
    if wanted == 'wanted'
      compared.each_with_index.map{|x, i| x if compared[i+1] == x}.compact
      compared = self.pub.kegs.avaiable_beers.last(3) if compared.empty?
    end
    compared.uniq
  end

end

app/controllers/taps_controller.rb
class TapsController < ApplicationController
load_and_authorize_resource
skip_before_action :pub_and_taps, only: [:new, :create]
  def show
    @tap = Tap.find(params[:id])
  end

  def create
     respond_to do |format|
       if Tap.new(tap_params).valid?
         new_taps = []
         params[:number].to_i.times do
           new_taps << Tap.new(tap_params)
         end
         new_taps.each(&:save)
         format.html { redirect_to taps_path, notice: 'Tap was successfully created.' }
         format.json { render :index, status: :created, location: @tap }
       else
         format.html { render :new }
         format.json { render json: @tap.errors, status: :unprocessable_entity }
       end
     end
   end

  def destroy
  end

  def edit
    @tap = Tap.find(params[:id])
  end

  def update
    @tap = Tap.find(params[:id])
    @tap.keg.destroy if @tap.keg
    @tap.keg = Keg.find(params[:keg_id])
    redirect_to taps_path
  end

  def index
    @taps = Tap.all
  end

  private

  def tap_params
    params.require(:tap).permit(
    :number, :pub_id, keg_attributes: [ :id ]
    )
  end
end

app/helpers/taps_helper.rb
module TapsHelper
end

app/views/taps/edit.html.erb
<h2>Kran <%= @tap.number%>: <%= @tap.keg.beer.name if @tap.keg%></h2>
<% if @tap.priorities.any? %>
  <h3>Priorities: </h3>
  <% @tap.priorities.each do |p| %>
    <ul><%= p.prioritize %><%= link_to "X", priority_path(p.id),
      method: :delete, data: {confirm: "Do you want to cancel this priority?"},
      class: 'btn btn-xs btn-danger' if can? :destroy, Priority %>
    </ul>
  <% end %>
<% end %>
<% if can? :create, Priority %>
  <%= render "priorities/new" %>
<% end %>
<h3>Replace current keg with:</h3>
<div>
  <%= form_for @tap do |f| %>
      <% @tap.beer_picker.each do |k| %>
        <% if k %>
        <div class="pick-beer">
            <%= f.submit 'Choose this beer', name: "keg_id", value: k.id %>
            <%= k.beer.name%>
          <date class='<%= k.expired? %>'><%= k.expiration_date %></date>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
<% if @tap.keg %>
  <h3><%=@tap.keg.beer.name %></h3>
  <date class='<%= @tap.keg.expired? %>'><%= @tap.keg.expiration_date %></date>
  <%= link_to "Untap current keg", keg_path(@tap.keg),
    method: :delete, data: {confirm: "Do you want to untap this keg without tapping a new one?"},
    class: 'btn btn-xs btn-danger' %>
<% end %>
<div>
  <script>
  $(document).ready(function(){
      $('<div class="btn cover-button"><p>Choose this beer</p></div>').insertAfter( $('.edit_tap input[type="submit"]') );
  });
  </script>

app/views/taps/index.html.erb
<h1>List of beers</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Beer</th>
      <th scope="col">Brewery</th>
      <th scope="col">Style</th>
      <th scope="col">Abv</th>
      <th scope="col">Blg</th>
      <th scope="col">IBU</th>
      <th scope="col">Price</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @taps.where(pub: current_user.pub).includes(keg: :beer).each do |tap| %>
    <% if tap.keg %>
      <% b = tap.keg.beer  %>
      <tr>
        <td><%= tap.number %></th>
        <td><%= b.name %></td>
        <td><%= b.brewery.name %></td>
        <td><%= b.style.name %></td>
        <td><%= b.abv %>%</td>
        <td><%= b.plato %>°</td>
        <td><%= b.ibu %></td>
        <td><%= b.price %></td>
        <td><%= link_to 'Tap new beer', edit_tap_path(tap) %></td>
      </tr>
    <% else %>
    <tr>
      <td><%= tap.number %></td>
      <% 7.times do %>
        <td> - </td>
      <% end %>
      <td><%= link_to 'Tap new beer', edit_tap_path(tap) %></td>
    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/taps/new.html.erb
<div class="centered-wrapper">
  <div class="sign-form col-xs-8 col-lg-4">
    <h2>How many taps are in <%= current_user.pub.name %>?</h2>
    <div class="content-wrapper">
      <%= form_for @tap do |f| %>
       <div class="field form-field">
        <%= number_field_tag :number, 1, in: 1..100 %>
      </div>
        <%= f.hidden_field :pub_id, value: current_user.pub_id %>

        <div class="actions">
          <%= f.submit "Confirm" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/taps/show.html.erb
  <%= render 'priorities/new'%>