config/routes.rb
Rails.application.routes.draw do

  get 'breweries/new'

  get 'breweries/create'

  get 'breweries/index'

  get 'breweries/destroy'

  root   'taps#index'
  resources :styles
  resources :breweries
  resources :pubs
  resources :priorities
  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => :my
  resources :users
  resources :kegs
  resources :beers
  resources :taps
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :brewery
  belongs_to :style
  has_many :kegs
  has_many :priorities, -> {where(p_type: :p_beer)}
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
load_and_authorize_resource
  def new
    @beer = Beer.new
  end

  def create
    @beer = Beer.create(beer_params)

     respond_to do |format|
       if @beer.save
         format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
         format.json { render :show, status: :created, location: @beer }
       else
         format.html { render :new }
         format.json { render json: @beer.errors, status: :unprocessable_entity }
       end
     end
   end

  def index
    @beers = Beer.all
  end

  def show
    @beer = Beer.find(params[:id])
  end

  private

  def beer_params
    params.require(:beer).permit(
    :name, :plato, :ibu, :abv, :price,
    :brewery_id, :style_id
    )
  end

end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/index.html.erb
<h1>List of beers</h1>
<% if can? :create, Beer %>
  <p><%= link_to 'Add new beer', new_beer_path %></p>
<% end %>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Beer</th>
      <th scope="col">Brewery</th>
      <th scope="col">Style</th>
      <th scope="col">Abv</th>
      <th scope="col">Blg</th>
      <th scope="col">IBU</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
  <% @beers.includes(:brewery, :style).each_with_index do |b, i| %>
    <tr>
      <td><%= i+1 %></th>
      <td><%= b.name %></td>
      <td><%= b.brewery.name %></td>
      <td><%= b.style.name %></td>
      <td><%= b.abv %>%</td>
      <td><%= b.plato %>°</td>
      <td><%= b.ibu %></td>
      <td><%= b.price %></td>
    </tr>
  <% end %>
  </tbody>
</table

app/views/beers/new.html.erb
<div class="centered-wrapper">
  <div class="sign-form col-xs-8 col-lg-4">
    <h2>Add new beer</h2>
    <div class="content-wrapper">
    <%= form_for @beer do |f| %>
    
      <% if @beer.errors.any? %>
        <div class='alert alert-danger' role='alert'>
          <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>
    
          <ul>
          <% beer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <div class="field form-field">  
      <%= f.label :name %>
      <%= f.text_field :name %>
   </div>  
    <div class="field form-field">
      <%= f.label :plato %>
      <%= f.number_field :plato %>
   </div>  
    <div class="field form-field">
      <%= f.label :ibu %>
      <%= f.number_field :ibu %>
   </div>  
    <div class="field form-field">
      <%= f.label :abv %>
      <%= f.number_field :abv, step: :any %>
   </div>  
    <div class="field form-field">
      <%= f.label :price %>
      <%= f.number_field :price %>
   </div>  
    <div class="field form-field">
      <%= f.label :brewery %>
        <% @breweries = Brewery.all %>
        <%= f.select :brewery_id,
            @breweries.map { |b| [b.name, b.id  ] }, {}, class: 'form-control' %>
    </div>  
    <div class="field form-field">
      <%= f.label :style %>
        <% @styles = Style.all %>
        <%= f.select :style_id,
            @styles.map { |s| [s.name, s.id  ] }, {}, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit "Confirm" %>
    </div>
    
    <% end %>
    </div>
  </div>
</div>

app/views/beers/show.html.erb
<%= @beer.name %>