config/routes.rb
Rails.application.routes.draw do

  get 'breweries/new'

  get 'breweries/create'

  get 'breweries/index'

  get 'breweries/destroy'

  root   'taps#index'
  resources :styles
  resources :breweries
  resources :pubs
  resources :priorities
  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => :my
  resources :users
  resources :kegs
  resources :beers
  resources :taps
end

app/views/layouts/_navbar.html.erb
<nav id="navi" class="navbar navbar-default navbar-fixed-top main-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><%= (current_user && current_user.pub) ? current_user.pub.name : 'Tap Manager' %> </a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Taps', taps_path %></li>
        <li><%= link_to 'Kegs', kegs_path %></li>
        <li><%= link_to 'Beers', beers_path %></li>
        <% if current_user.admin? || current_user.manager? %>
          <li><%= link_to 'Breweries', breweries_path %></li>
          <li><%= link_to 'Styles', styles_path %></li>
        <% end %>
        <% if can? :index, User %>
          <li><%= link_to 'Crew', users_path %></li>
        <% end %>
        <li><%= link_to current_user.email, beers_path %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, role: 'button' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TapManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>